apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: kafka-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-connect
  endpoints:
  - port: 9404
    interval: 30s
    metricRelabeling:
    # - separator: ;
    #   regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
    #   replacement: $1
    #   action: labelmap
    # - sourceLabels: [__meta_kubernetes_namespace]
    #   separator: ;
    #   regex: (.*)
    #   targetLabel: namespace
    #   replacement: $1
    #   action: replace
    - sourceLabels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      targetLabel: kubernetes_pod_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_host_ip]
      separator: ;
      regex: (.*)
      targetLabel: node_ip
      replacement: $1
      action: replace